// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomeCarousel: typeof import('./components/home/HomeCarousel.vue')['default']
    HomeCTA: typeof import('./components/home/HomeCTA.vue')['default']
    HomeFeatures: typeof import('./components/home/HomeFeatures.vue')['default']
    HomeMain: typeof import('./components/home/HomeMain.vue')['default']
    HomeNeeds: typeof import('./components/home/HomeNeeds.vue')['default']
    HomePadi: typeof import('./components/home/HomePadi.vue')['default']
    HomeSignup: typeof import('./components/home/HomeSignup.vue')['default']
    HomeTimeline: typeof import('./components/home/HomeTimeline.vue')['default']
    Illus01: typeof import('./components/home/Illus01.vue')['default']
    TheFooter: typeof import('./components/navbar/TheFooter.vue')['default']
    TheHeader: typeof import('./components/navbar/TheHeader.vue')['default']
  }
}
